In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Load the dataset (df)

In [8]:
df=pd.read_csv("/content/apple_sales_2024.csv")
df

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

# Save to excel file

In [9]:
df.to_excel("output.xlsx")

In [10]:
df

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

# Exploring Data

In [11]:
df.head() # First 5 rows

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29

In [12]:
df.nunique() # count of unique values in each columns

State                               25
Region                               5
iPhone Sales (in million units)    824
iPad Sales (in million units)      692
Mac Sales (in million units)       595
Wearables (in million units)       639
Services Revenue (in billion $)    741
dtype: int64

In [13]:
df.sample() # Random cell

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
342,Illinois,North America,27.26,7.38,7.37,11.43,16.06

In [14]:
df.tail() # last 5 rows

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

In [15]:
df.index # Row index

RangeIndex(start=0, stop=1000, step=1)

In [16]:
df.shape # rows and columns

(1000, 7)

In [17]:
df.describe() # Statistical summary

,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,17.444500,8.565880,5.555760,6.935500,12.447130
std,7.180077,3.735994,2.506491,2.951677,4.306347
min,5.030000,2.020000,1.010000,2.000000,5.010000
25%,11.447500,5.432500,3.470000,4.330000,8.710000
50%,17.130000,8.695000,5.550000,6.815000,12.205000
75%,23.715000,11.740000,7.730000,9.532500,16.252500
max,29.940000,14.990000,9.990000,12.000000,19.920000

In [18]:
df.info() # summary info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   State                            1000 non-null   object
 1   Region                           1000 non-null   object
 2   iPhone Sales (in million units)  1000 non-null   float64
 3   iPad Sales (in million units)    1000 non-null   float64
 4   Mac Sales (in million units)     1000 non-null   float64
 5   Wearables (in million units)     1000 non-null   float64
 6   Services Revenue (in billion $)  1000 non-null   float64
dtypes: float64(5), object(2)
memory usage: 54.8+ KB

In [19]:
df.columns # column names

Index(['State', 'Region', 'iPhone Sales (in million units)',
       'iPad Sales (in million units)', 'Mac Sales (in million units)',
       'Wearables (in million units)', 'Services Revenue (in billion $)'],
      dtype='object')

In [20]:
df.isnull().sum() # count of null values in each columns

State                              0
Region                             0
iPhone Sales (in million units)    0
iPad Sales (in million units)      0
Mac Sales (in million units)       0
Wearables (in million units)       0
Services Revenue (in billion $)    0
dtype: int64

In [21]:
df.dtypes # data types of each column

State                               object
Region                              object
iPhone Sales (in million units)    float64
iPad Sales (in million units)      float64
Mac Sales (in million units)       float64
Wearables (in million units)       float64
Services Revenue (in billion $)    float64
dtype: object

# Dataframe creation

In [22]:
data = {'Product':['iphone','ipad'],'Sales':[100,80]}
pd.DataFrame(data)

  Product  Sales
0  iphone    100
1    ipad     80

# Data cleaning

In [23]:
df.duplicated().sum() #count of duplicate rows

np.int64(0)

In [24]:
df.fillna(0,inplace=True) # fill all missing values to 0
df

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,Greater China,7.46,6.75,1.19,5.88,15.88
1,Germany,Europe,8.63,14.06,7.03,7.42,10.12
2,UK,Europe,5.61,14.09,8.78,8.19,19.85
3,Shanghai,Greater China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,Europe,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,Greater China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,Greater China,26.30,4.06,3.41,5.69,14.29

In [25]:
df.replace({'Europe':'EU','Greater China':'China'},inplace=True) #  Change the name in particular column
df

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [26]:
# rename column to make easier to use
df.rename(columns={'iPhone Sales (in million units)':'iphone_sales',
                   'iPad Sales (in million units)':'ipad_sales',
                   'Mac Sales (in million units)':'mac_sales',
                   'Wearables (in million units)':'wearables',
                   'Services Revenue (in billion $)':'Service_revenue'},inplace=True)
df.head()

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29

In [27]:
# convert columns to float types for numeric operations
df=df.astype({'iphone_sales':'float',
              'ipad_sales':'float',
              'mac_sales':'float',
              'wearables':'float',
              'Service_revenue':'float'})
df

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

# Data selection and filtering

In [28]:
df['Region'] # select a single column

0              China
1                 EU
2                 EU
3              China
4       Rest of Asia
           ...
995    Rest of World
996    North America
997               EU
998            China
999            China
Name: Region, Length: 1000, dtype: object

In [29]:
df[['Region','iphone_sales']] # select multiple columns

            Region  iphone_sales
0            China          7.46
1               EU          8.63
2               EU          5.61
3            China          7.82
4     Rest of Asia         16.70
..             ...           ...
995  Rest of World         29.86
996  North America         27.83
997             EU         25.47
998          China         15.34
999          China         26.30

[1000 rows x 2 columns]

In [30]:
df.iloc[0] # select the first row using index postion

State              Chongqing
Region                 China
iphone_sales            7.46
ipad_sales              6.75
mac_sales               1.19
wearables               5.88
Service_revenue        15.88
Name: 0, dtype: object

In [31]:
df.iloc[0:5] # iloc - index location, select the first 5 rows

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29

In [32]:
df.loc[0,'Region'] # loc - label based selection , get the value in row 0 and column 'region'

'China'

In [33]:
df[df['iphone_sales']>10] # filter rows where iphone_sales is greater than 10

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
5,Chongqing,China,12.18,10.97,9.38,11.65,12.70
6,UK,EU,25.47,7.41,7.18,7.56,17.20
7,New York,North America,22.37,6.74,4.39,3.22,16.07
8,Mexico,Rest of World,20.80,6.79,4.99,2.68,8.69
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [34]:
# filter row where state is UK and Iphone sales > 20
df[(df['State']=='UK')& (df['iphone_sales']>20)]

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
6,UK,EU,25.47,7.41,7.18,7.56,17.20
35,UK,EU,23.34,9.22,6.47,10.89,15.56
47,UK,EU,24.97,5.38,4.70,2.89,5.50
58,UK,EU,20.84,2.74,1.83,6.00,5.33
65,UK,EU,26.58,7.73,5.96,10.36,14.72
180,UK,EU,22.52,9.00,5.55,10.26,19.37
200,UK,EU,25.52,11.80,3.57,6.90,13.48
436,UK,EU,25.68,14.39,5.95,4.97,13.95
500,UK,EU,27.39,11.38,7.16,3.76,13.39
536,UK,EU,21.56,11.89,5.05,4.32,12.15
543,UK,EU,22.18,2.47,3.53,3.84,14.24
577,UK,EU,29.73,3.50,8.74,2.04,11.96
600,UK,EU,22.94,11.84,8.65,8.07,5.33
683,UK,EU,25.12,6.11,6.30,5.83,8.97
709,UK,EU,23.52,8.37,4.52,2.62,12.02
867,UK,EU,20.76,6.71,1.92,8.41,19.10
899,UK,EU,21.97,7.99,5.25,10.71,5.49
923,UK,EU,20.60,11.67,7.52,10.41,8.78
975,UK,EU,26.75,10.88,1.18,3.21,13.62

In [35]:
df[df['Region'].isin(['China','EU'])]

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
5,Chongqing,China,12.18,10.97,9.38,11.65,12.70
...,...,...,...,...,...,...,...
990,Spain,EU,22.06,10.18,5.90,5.59,12.13
992,Beijing,China,7.20,12.62,3.97,9.87,10.02
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [36]:
# exclude row where the region is UK
df[~df['State'].isin(['UK'])]

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
5,Chongqing,China,12.18,10.97,9.38,11.65,12.70
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [37]:
df[df['State'].str.contains('New')] # filter rows where the state column contains the word new

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
7,New York,North America,22.37,6.74,4.39,3.22,16.07
38,New York,North America,25.20,14.40,8.00,3.31,16.93
70,New York,North America,23.19,5.47,4.97,6.61,15.84
78,New York,North America,21.51,12.58,9.46,6.62,6.02
98,New York,North America,8.66,6.15,3.11,4.44,10.53
211,New York,North America,21.63,6.61,8.42,10.78,11.27
247,New York,North America,22.32,10.50,6.36,4.12,15.47
297,New York,North America,10.51,8.38,4.59,3.55,7.12
326,New York,North America,6.99,9.92,3.96,11.69,5.22
339,New York,North America,21.11,14.06,6.39,6.51,17.43
380,New York,North America,17.96,14.79,5.38,8.93,18.16
401,New York,North America,7.38,14.85,4.67,9.15,6.81
410,New York,North America,9.14,7.02,4.42,11.98,6.19
422,New York,North America,5.88,14.83,9.34,3.91,18.49
425,New York,North America,11.52,12.38,5.22,7.11,8.62
440,New York,North America,12.41,6.00,7.24,11.47,16.26
461,New York,North America,24.79,11.20,7.34,2.36,19.11
490,New York,North America,21.46,14.34,2.02,7.55,14.15
494,New York,North America,8.79,5.68,5.43,9.52,9.49
520,New York,North America,29.45,5.29,8.75,8.13,19.26
544,New York,North America,14.95,14.47,1.69,10.05,14.62
575,New York,North America,28.05,7.01,5.86,3.56,5.79
591,New York,North America,12.95,13.03,6.17,9.10,12.21
662,New York,North America,9.59,3.29,5.59,7.09,8.56
686,New York,North America,15.05,5.17,6.60,3.26,14.13
690,New York,North America,13.88,2.64,6.23,5.25,13.76
748,New York,North America,8.52,5.33,1.14,7.30,18.08
776,New York,North America,16.89,11.77,6.50,6.01,10.32
781,New York,North America,13.44,12.15,5.42,3.78,18.50
805,New York,North America,23.52,12.05,7.40,2.95,15.72
822,New York,North America,17.10,3.05,2.49,9.17,18.13
881,New York,North America,13.06,9.02,8.62,4.75,10.67
883,New York,North America,5.07,5.37,5.42,5.93,17.85
889,New York,North America,17.59,6.79,9.30,9.43,8.24
908,New York,North America,11.10,11.74,5.19,3.84,12.36
945,New York,North America,9.77,8.79,7.75,10.52,6.65
979,New York,North America,16.49,3.32,9.93,7.99,7.06

# Sorting & indexing

## sorting rows by values

In [38]:
# sort rows in ascending order of iphone sales
df.sort_values(by='iphone_sales')

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
787,Shanghai,China,5.03,8.79,4.26,6.34,11.05
777,Mexico,Rest of World,5.05,11.92,4.29,10.91,7.80
883,New York,North America,5.07,5.37,5.42,5.93,17.85
789,South Africa,Rest of World,5.13,6.18,9.91,8.51,14.34
502,Texas,North America,5.14,8.35,6.85,6.24,19.78
...,...,...,...,...,...,...,...
151,Shenzhen,China,29.84,5.28,3.67,9.12,6.29
34,Brazil,Rest of World,29.86,9.45,9.67,3.92,6.25
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
866,Indonesia,Rest of Asia,29.92,2.07,5.05,2.68,8.50
743,Italy,EU,29.94,14.17,1.40,9.29,5.27

In [39]:
# sort rows in descending order
df.sort_values(by='iphone_sales',ascending=False)

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
743,Italy,EU,29.94,14.17,1.40,9.29,5.27
866,Indonesia,Rest of Asia,29.92,2.07,5.05,2.68,8.50
34,Brazil,Rest of World,29.86,9.45,9.67,3.92,6.25
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
151,Shenzhen,China,29.84,5.28,3.67,9.12,6.29
...,...,...,...,...,...,...,...
502,Texas,North America,5.14,8.35,6.85,6.24,19.78
789,South Africa,Rest of World,5.13,6.18,9.91,8.51,14.34
883,New York,North America,5.07,5.37,5.42,5.93,17.85
777,Mexico,Rest of World,5.05,11.92,4.29,10.91,7.80
787,Shanghai,China,5.03,8.79,4.26,6.34,11.05

In [40]:
# sort the state (A - Z) then by iphone sales( hugh to low)
df.sort_values(by=['State','iphone_sales'],ascending=[True,False])

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
934,Australia,Rest of World,27.78,9.02,4.87,7.86,13.78
299,Australia,Rest of World,27.31,13.88,2.04,4.64,19.19
488,Australia,Rest of World,25.92,11.34,1.78,5.50,8.95
767,Australia,Rest of World,25.70,3.87,6.57,8.44,9.86
259,Australia,Rest of World,24.90,9.84,7.30,11.03,9.36
...,...,...,...,...,...,...,...
216,UK,EU,6.61,10.26,8.61,7.27,9.40
400,UK,EU,6.57,11.26,8.33,4.53,8.92
614,UK,EU,6.35,9.83,8.90,5.62,14.34
2,UK,EU,5.61,14.09,8.78,8.19,19.85
677,UK,EU,5.61,2.96,7.70,2.63,16.48

## sorting by index

In [41]:
df.sort_index(ascending=False) # sort rows by index in descending order

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
...,...,...,...,...,...,...,...
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
2,UK,EU,5.61,14.09,8.78,8.19,19.85
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88

In [42]:
df.sort_index() # sort rows by index in ascending order

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

## setting an index

In [43]:
# set state column as index ( does not chnage the OG df)
df.set_index('State')

,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
State,,,,,,
Chongqing,China,7.46,6.75,1.19,5.88,15.88
Germany,EU,8.63,14.06,7.03,7.42,10.12
UK,EU,5.61,14.09,8.78,8.19,19.85
Shanghai,China,7.82,7.97,9.78,2.28,6.16
Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...
Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
Texas,North America,27.83,12.52,8.89,4.46,6.38
Germany,EU,25.47,7.69,7.90,6.90,15.00
Shenzhen,China,15.34,8.81,8.24,8.78,15.49
Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [44]:
# set state as index and update df directly
# df.set_index('State',inplace=False)
# df

In [45]:
# set multiple cloumns as hierarchical
# df.set_index(['Region','State'],inplace=False)
# df

## resetting the index

In [46]:
# reset index to default integers and keep old index as a column
df.reset_index()

,index,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...,...
995,995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

In [47]:
#  reset index and remove the old index completely
df.reset_index(drop=True)

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29

## reindexing

In [48]:
# reorder rows to new custom index order
df.reindex([2,0,1])

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
2,UK,EU,5.61,14.09,8.78,8.19,19.85
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Germany,EU,8.63,14.06,7.03,7.42,10.12

In [49]:
# reorder columns in a custom order
df.reindex(columns=['State','Region','Service_revenue'])

         State         Region  Service_revenue
0    Chongqing          China            15.88
1      Germany             EU            10.12
2           UK             EU            19.85
3     Shanghai          China             6.16
4     Thailand   Rest of Asia            13.29
..         ...            ...              ...
995     Mexico  Rest of World            18.56
996      Texas  North America             6.38
997    Germany             EU            15.00
998   Shenzhen          China            15.49
999   Shanghai          China            14.29

[1000 rows x 3 columns]

# Aggregation & Grouping

## Groupby one column

In [50]:
df.groupby('Region').size()

Region
China            219
EU               204
North America    178
Rest of Asia     178
Rest of World    221
dtype: int64

In [51]:
# total sum of all numeric columns grouped by state
df.groupby('State').sum()

,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
State,,,,,,
Australia,Rest of WorldRest of WorldRest of WorldRest of...,642.96,393.68,238.93,267.50,541.19
Beijing,ChinaChinaChinaChinaChinaChinaChinaChinaChinaC...,757.27,344.28,238.24,284.83,532.03
Brazil,Rest of WorldRest of WorldRest of WorldRest of...,844.50,405.45,240.84,328.77,523.41
California,North AmericaNorth AmericaNorth AmericaNorth A...,843.34,459.86,250.88,345.03,591.67
Canada,Rest of WorldRest of WorldRest of WorldRest of...,784.68,332.87,263.73,299.30,550.15
Chongqing,ChinaChinaChinaChinaChinaChinaChinaChinaChinaC...,652.60,361.54,209.76,281.00,535.93
Florida,North AmericaNorth AmericaNorth AmericaNorth A...,479.70,228.39,164.49,196.67,324.07
France,EUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEU...,724.19,326.43,229.74,351.72,550.11
Germany,EUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEU...,658.35,308.73,212.28,224.01,419.05
Hong Kong,ChinaChinaChinaChinaChinaChinaChinaChinaChinaC...,934.06,463.24,268.37,352.83,631.51
Illinois,North AmericaNorth AmericaNorth AmericaNorth A...,658.04,296.34,208.92,246.67,468.27
India,Rest of AsiaRest of AsiaRest of AsiaRest of As...,520.97,267.11,182.45,231.69,414.79
Indonesia,Rest of AsiaRest of AsiaRest of AsiaRest of As...,680.71,301.09,199.31,276.69,458.83
Italy,EUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEU...,671.20,352.98,199.27,248.72,450.80
Japan,Rest of AsiaRest of AsiaRest of AsiaRest of As...,739.25,335.51,222.86,296.20,518.63
Mexico,Rest of WorldRest of WorldRest of WorldRest of...,693.92,362.07,212.97,276.34,486.78
New York,North AmericaNorth AmericaNorth AmericaNorth A...,579.29,336.18,220.76,250.94,471.09
Shanghai,ChinaChinaChinaChinaChinaChinaChinaChinaChinaC...,758.20,318.20,259.22,284.82,548.40
Shenzhen,ChinaChinaChinaChinaChinaChinaChinaChinaChinaC...,766.15,375.69,237.21,311.38,532.85
South Africa,Rest of WorldRest of WorldRest of WorldRest of...,831.40,364.50,263.37,326.40,600.22
South Korea,Rest of AsiaRest of AsiaRest of AsiaRest of As...,635.28,296.36,190.95,235.68,464.21
Spain,EUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEU...,699.07,353.52,189.80,239.48,427.29
Texas,North AmericaNorth AmericaNorth AmericaNorth A...,563.77,304.67,183.91,233.61,426.11
Thailand,Rest of AsiaRest of AsiaRest of AsiaRest of As...,515.29,273.19,187.37,256.03,410.69
UK,EUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEUEU...,810.31,404.00,280.13,289.19,569.05

In [52]:
# groupby both region and state then get sum
df.groupby('Region')['State'].sum()

Region
China            ChongqingShanghaiChongqingHong KongHong KongCh...
EU               GermanyUKUKItalySpainSpainGermanyUKSpainUKUKUK...
North America    New YorkTexasCaliforniaCaliforniaCaliforniaNew...
Rest of Asia     ThailandJapanJapanIndiaJapanSouth KoreaSouth K...
Rest of World    MexicoCanadaAustraliaAustraliaAustraliaSouth A...
Name: State, dtype: object

## range

In [53]:
# range (max-min) of iPad sales for each region
df.groupby('Region')['ipad_sales'].max() - df.groupby('Region')['ipad_sales'].min()

Region
China            12.65
EU               12.96
North America    12.91
Rest of Asia     12.87
Rest of World    12.88
Name: ipad_sales, dtype: float64

## Groupby by multiple columns

In [54]:
#  groupby both region and state, then get average
df.groupby(['Region','State']).mean()

                            iphone_sales  ipad_sales  mac_sales  wearables  \
Region        State
China         Beijing          17.610930    8.006512   5.540465   6.623953
              Chongqing        16.315000    9.038500   5.244000   7.025000
              Hong Kong        18.681200    9.264800   5.367400   7.056600
              Shanghai         17.632558    7.400000   6.028372   6.623721
              Shenzhen         17.817442    8.736977   5.516512   7.241395
EU            France           16.841628    7.591395   5.342791   8.179535
              Germany          17.793243    8.344054   5.737297   6.054324
              Italy            17.663158    9.288947   5.243947   6.545263
              Spain            17.924872    9.064615   4.866667   6.140513
              UK               17.240638    8.595745   5.960213   6.152979
North America California       17.943404    9.784255   5.337872   7.341064
              Florida          18.450000    8.784231   6.326538   7.564231
              Illinois         18.801143    8.466857   5.969143   7.047714
              New York         15.656486    9.085946   5.966486   6.782162
              Texas            17.083939    9.232424   5.573030   7.079091
Rest of Asia  India            15.786970    8.094242   5.528788   7.020909
              Indonesia        17.913421    7.923421   5.245000   7.281316
              Japan            18.481250    8.387750   5.571500   7.405000
              South Korea      18.684706    8.716471   5.616176   6.931765
              Thailand         15.614848    8.278485   5.677879   7.758485
Rest of World Australia        14.952558    9.155349   5.556512   6.220930
              Brazil           18.358696    8.814130   5.235652   7.147174
              Canada           17.058261    7.236304   5.733261   6.506522
              Mexico           17.792821    9.283846   5.460769   7.085641
              South Africa     17.689362    7.755319   5.603617   6.944681

                            Service_revenue
Region        State
China         Beijing             12.372791
              Chongqing           13.398250
              Hong Kong           12.630200
              Shanghai            12.753488
              Shenzhen            12.391860
EU            France              12.793256
              Germany             11.325676
              Italy               11.863158
              Spain               10.956154
              UK                  12.107447
North America California          12.588723
              Florida             12.464231
              Illinois            13.379143
              New York            12.732162
              Texas               12.912424
Rest of Asia  India               12.569394
              Indonesia           12.074474
              Japan               12.965750
              South Korea         13.653235
              Thailand            12.445152
Rest of World Australia           12.585814
              Brazil              11.378478
              Canada              11.959783
              Mexico              12.481538
              South Africa        12.770638

## custom agregations with agg()

In [55]:
# sum and average
df.groupby('Region').agg({'iphone_sales':'sum','ipad_sales':'mean'})

               iphone_sales  ipad_sales
Region
China               3868.28    8.506621
EU                  3563.12    8.557157
North America       3124.14    9.131685
Rest of Asia        3091.50    8.276742
Rest of World       3797.46    8.409819

In [56]:
# get min,max and mean for all numeric columns per region
df.groupby('Region')['ipad_sales'].agg(['min','max','mean'])

                min    max      mean
Region
China          2.34  14.99  8.506621
EU             2.02  14.98  8.557157
North America  2.07  14.98  9.131685
Rest of Asia   2.04  14.91  8.276742
Rest of World  2.11  14.99  8.409819

## value counts ( like group counts)

In [57]:
# count how many times each region appears
df['Region'].value_counts()

Region
Rest of World    221
China            219
EU               204
Rest of Asia     178
North America    178
Name: count, dtype: int64

In [58]:
# same as value_counts but works with groupby
df.groupby('State').value_counts()

State      Region         iphone_sales  ipad_sales  mac_sales  wearables  Service_revenue
Australia  Rest of World  5.15          8.54        3.21       7.33       5.56               1
                          5.63          5.92        2.45       4.82       9.42               1
                          6.00          8.95        5.34       8.64       17.24              1
                          6.49          5.45        4.03       3.42       7.18               1
                          6.79          6.06        2.31       10.51      14.45              1
                                                                                            ..
UK         EU             25.68         14.39       5.95       4.97       13.95              1
                          26.58         7.73        5.96       10.36      14.72              1
                          26.75         10.88       1.18       3.21       13.62              1
                          27.39         11.38       7.16       3.76       13.39              1
                          29.73         3.50        8.74       2.04       11.96              1
Name: count, Length: 1000, dtype: int64

## using pivot_table()

In [59]:
# create pivot table : region as rows state as columns
df.pivot_table(values='iphone_sales',index='Region',columns='State')

State,Australia,Beijing,Brazil,California,Canada,Chongqing,Florida,France,Germany,Hong Kong,...,Mexico,New York,Shanghai,Shenzhen,South Africa,South Korea,Spain,Texas,Thailand,UK
Region,,,,,,,,,,,,,,,,,,,,,
China,NaN,17.61093,NaN,NaN,NaN,16.315,NaN,NaN,NaN,18.6812,...,NaN,NaN,17.632558,17.817442,NaN,NaN,NaN,NaN,NaN,NaN
EU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.841628,17.793243,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17.924872,NaN,NaN,17.240638
North America,NaN,NaN,NaN,17.943404,NaN,NaN,18.45,NaN,NaN,NaN,...,NaN,15.656486,NaN,NaN,NaN,NaN,NaN,17.083939,NaN,NaN
Rest of Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.684706,NaN,NaN,15.614848,NaN
Rest of World,14.952558,NaN,18.358696,NaN,17.058261,NaN,NaN,NaN,NaN,NaN,...,17.792821,NaN,NaN,NaN,17.689362,NaN,NaN,NaN,NaN,NaN

In [60]:
# pivot with total iphone sales per state
df.pivot_table(values='iphone_sales',index='State',aggfunc='sum')

              iphone_sales
State
Australia           642.96
Beijing             757.27
Brazil              844.50
California          843.34
Canada              784.68
Chongqing           652.60
Florida             479.70
France              724.19
Germany             658.35
Hong Kong           934.06
Illinois            658.04
India               520.97
Indonesia           680.71
Italy               671.20
Japan               739.25
Mexico              693.92
New York            579.29
Shanghai            758.20
Shenzhen            766.15
South Africa        831.40
South Korea         635.28
Spain               699.07
Texas               563.77
Thailand            515.29
UK                  810.31

## crosstab for frequency

In [61]:
# frequency table: how many times each region-state pair occurs
pd.crosstab(df['Region'],df['State'])

State,Australia,Beijing,Brazil,California,Canada,Chongqing,Florida,France,Germany,Hong Kong,...,Mexico,New York,Shanghai,Shenzhen,South Africa,South Korea,Spain,Texas,Thailand,UK
Region,,,,,,,,,,,,,,,,,,,,,
China,0,43,0,0,0,40,0,0,0,50,...,0,0,43,43,0,0,0,0,0,0
EU,0,0,0,0,0,0,0,43,37,0,...,0,0,0,0,0,0,39,0,0,47
North America,0,0,0,47,0,0,26,0,0,0,...,0,37,0,0,0,0,0,33,0,0
Rest of Asia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,34,0,0,33,0
Rest of World,43,0,46,0,46,0,0,0,0,0,...,39,0,0,0,47,0,0,0,0,0

# Merging and joining

In [63]:
df1=pd.read_csv('/content/samsung_sales_1000_rows.csv')
df1

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $)
0,Incheon,South Korea,8.28,7.18,1.18,6.31,17.49
1,Jeonju,South Korea,10.34,12.86,6.68,6.39,11.61
2,Daegu,South Korea,4.57,15.73,7.26,8.07,19.01
3,Gwangju,South Korea,8.18,7.92,9.52,2.09,6.95
4,Incheon,South Korea,19.19,6.57,5.81,3.50,12.16
...,...,...,...,...,...,...,...
995,Suwon,South Korea,35.23,11.72,6.18,7.88,16.11
996,Daejeon,South Korea,30.57,11.48,8.89,4.58,5.85
997,Daejeon,South Korea,25.72,6.33,7.95,6.80,17.23
998,Busan,South Korea,15.47,7.68,6.80,9.99,12.74
999,Suwon,South Korea,29.56,3.45,3.71,5.86,14.42

## Concatenation

In [64]:
# stack two dataframe vertically ( same columns)
pd.concat([df1,df])

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $),iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Incheon,South Korea,8.28,7.18,1.18,6.31,17.49,NaN,NaN,NaN,NaN,NaN
1,Jeonju,South Korea,10.34,12.86,6.68,6.39,11.61,NaN,NaN,NaN,NaN,NaN
2,Daegu,South Korea,4.57,15.73,7.26,8.07,19.01,NaN,NaN,NaN,NaN,NaN
3,Gwangju,South Korea,8.18,7.92,9.52,2.09,6.95,NaN,NaN,NaN,NaN,NaN
4,Incheon,South Korea,19.19,6.57,5.81,3.50,12.16,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Mexico,Rest of World,NaN,NaN,NaN,NaN,NaN,29.86,10.30,7.40,9.60,18.56
996,Texas,North America,NaN,NaN,NaN,NaN,NaN,27.83,12.52,8.89,4.46,6.38
997,Germany,EU,NaN,NaN,NaN,NaN,NaN,25.47,7.69,7.90,6.90,15.00
998,Shenzhen,China,NaN,NaN,NaN,NaN,NaN,15.34,8.81,8.24,8.78,15.49
999,Shanghai,China,NaN,NaN,NaN,NaN,NaN,26.30,4.06,3.41,5.69,14.29

In [65]:
# stack tow dataframe side by side (column wise)
pd.concat([df1,df],axis=1)

,State,Region,iPhone Sales (in million units),iPad Sales (in million units),Mac Sales (in million units),Wearables (in million units),Services Revenue (in billion $),State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue
0,Incheon,South Korea,8.28,7.18,1.18,6.31,17.49,Chongqing,China,7.46,6.75,1.19,5.88,15.88
1,Jeonju,South Korea,10.34,12.86,6.68,6.39,11.61,Germany,EU,8.63,14.06,7.03,7.42,10.12
2,Daegu,South Korea,4.57,15.73,7.26,8.07,19.01,UK,EU,5.61,14.09,8.78,8.19,19.85
3,Gwangju,South Korea,8.18,7.92,9.52,2.09,6.95,Shanghai,China,7.82,7.97,9.78,2.28,6.16
4,Incheon,South Korea,19.19,6.57,5.81,3.50,12.16,Thailand,Rest of Asia,16.70,8.13,6.46,3.48,13.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Suwon,South Korea,35.23,11.72,6.18,7.88,16.11,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56
996,Daejeon,South Korea,30.57,11.48,8.89,4.58,5.85,Texas,North America,27.83,12.52,8.89,4.46,6.38
997,Daejeon,South Korea,25.72,6.33,7.95,6.80,17.23,Germany,EU,25.47,7.69,7.90,6.90,15.00
998,Busan,South Korea,15.47,7.68,6.80,9.99,12.74,Shenzhen,China,15.34,8.81,8.24,8.78,15.49
999,Suwon,South Korea,29.56,3.45,3.71,5.86,14.42,Shanghai,China,26.30,4.06,3.41,5.69,14.29

## Merge by key column

In [66]:
# merge two dataframe where state column matches
pd.merge(df,df,on='State')

,State,Region_x,iphone_sales_x,ipad_sales_x,mac_sales_x,wearables_x,Service_revenue_x,Region_y,iphone_sales_y,ipad_sales_y,mac_sales_y,wearables_y,Service_revenue_y
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,7.46,6.75,1.19,5.88,15.88
1,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,12.18,10.97,9.38,11.65,12.70
2,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,7.92,8.77,5.19,3.08,16.14
3,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,11.79,7.05,8.33,11.81,15.66
4,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,19.66,11.05,4.60,5.84,12.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40791,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,22.67,4.42,8.99,10.48,16.31
40792,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,14.13,3.50,5.99,2.34,17.03
40793,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,11.01,11.05,3.33,11.64,11.95
40794,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,20.20,14.54,2.52,6.01,9.31
40795,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,26.30,4.06,3.41,5.69,14.29

In [ ]:
# left join (keep all rows from first df)
pd.merge(df,df,how='left',on='State')

In [67]:
# right join (keep all the rows from second df)
pd.merge(df,df,how='right',on='State')

,State,Region_x,iphone_sales_x,ipad_sales_x,mac_sales_x,wearables_x,Service_revenue_x,Region_y,iphone_sales_y,ipad_sales_y,mac_sales_y,wearables_y,Service_revenue_y
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,7.46,6.75,1.19,5.88,15.88
1,Chongqing,China,12.18,10.97,9.38,11.65,12.70,China,7.46,6.75,1.19,5.88,15.88
2,Chongqing,China,7.92,8.77,5.19,3.08,16.14,China,7.46,6.75,1.19,5.88,15.88
3,Chongqing,China,11.79,7.05,8.33,11.81,15.66,China,7.46,6.75,1.19,5.88,15.88
4,Chongqing,China,19.66,11.05,4.60,5.84,12.82,China,7.46,6.75,1.19,5.88,15.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40791,Shanghai,China,22.67,4.42,8.99,10.48,16.31,China,26.30,4.06,3.41,5.69,14.29
40792,Shanghai,China,14.13,3.50,5.99,2.34,17.03,China,26.30,4.06,3.41,5.69,14.29
40793,Shanghai,China,11.01,11.05,3.33,11.64,11.95,China,26.30,4.06,3.41,5.69,14.29
40794,Shanghai,China,20.20,14.54,2.52,6.01,9.31,China,26.30,4.06,3.41,5.69,14.29
40795,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,26.30,4.06,3.41,5.69,14.29

In [ ]:
# outer join (keep all the rows from both df)
pd.merge(df,df,how='outer',on='State')

In [1]:
# inner join (only matching rows)
pd.merge(df,df,how='inner',on='State')

NameError: name 'pd' is not defined

## Merge with different column names

In [69]:
#  merge where df['sate'] == df['state']
pd.merge(df,df,left_on='State',right_on='State')

,State,Region_x,iphone_sales_x,ipad_sales_x,mac_sales_x,wearables_x,Service_revenue_x,Region_y,iphone_sales_y,ipad_sales_y,mac_sales_y,wearables_y,Service_revenue_y
0,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,7.46,6.75,1.19,5.88,15.88
1,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,12.18,10.97,9.38,11.65,12.70
2,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,7.92,8.77,5.19,3.08,16.14
3,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,11.79,7.05,8.33,11.81,15.66
4,Chongqing,China,7.46,6.75,1.19,5.88,15.88,China,19.66,11.05,4.60,5.84,12.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40791,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,22.67,4.42,8.99,10.48,16.31
40792,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,14.13,3.50,5.99,2.34,17.03
40793,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,11.01,11.05,3.33,11.64,11.95
40794,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,20.20,14.54,2.52,6.01,9.31
40795,Shanghai,China,26.30,4.06,3.41,5.69,14.29,China,26.30,4.06,3.41,5.69,14.29

## Indicator for join type

In [70]:
# add a column showing the source of each row: left_only, right_only,both
pd.merge(df,df,on='State',how='outer',indicator=True)

,State,Region_x,iphone_sales_x,ipad_sales_x,mac_sales_x,wearables_x,Service_revenue_x,Region_y,iphone_sales_y,ipad_sales_y,mac_sales_y,wearables_y,Service_revenue_y,_merge
0,Australia,Rest of World,8.10,13.87,7.77,10.79,6.90,Rest of World,8.10,13.87,7.77,10.79,6.90,both
1,Australia,Rest of World,8.10,13.87,7.77,10.79,6.90,Rest of World,10.45,3.08,7.61,8.00,15.76,both
2,Australia,Rest of World,8.10,13.87,7.77,10.79,6.90,Rest of World,16.36,14.36,2.98,7.38,13.66,both
3,Australia,Rest of World,8.10,13.87,7.77,10.79,6.90,Rest of World,5.63,5.92,2.45,4.82,9.42,both
4,Australia,Rest of World,8.10,13.87,7.77,10.79,6.90,Rest of World,13.33,5.50,6.30,8.41,19.58,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40791,UK,EU,26.75,10.88,1.18,3.21,13.62,EU,18.40,11.23,5.62,6.55,18.63,both
40792,UK,EU,26.75,10.88,1.18,3.21,13.62,EU,21.97,7.99,5.25,10.71,5.49,both
40793,UK,EU,26.75,10.88,1.18,3.21,13.62,EU,20.60,11.67,7.52,10.41,8.78,both
40794,UK,EU,26.75,10.88,1.18,3.21,13.62,EU,13.04,7.61,9.17,8.64,15.66,both
40795,UK,EU,26.75,10.88,1.18,3.21,13.62,EU,26.75,10.88,1.18,3.21,13.62,both

# Operations and calculations

## basic column-wise calculations

In [71]:
# total of iphone_sales
df['iphone_sales'].sum()

np.float64(17444.5)

In [72]:
# average of iphone sales
df['iphone_sales'].mean()

np.float64(17.4445)

In [73]:
# highest value of iphone sales
df['iphone_sales'].max()

29.94

In [74]:
# lowest values of iphone sales
df['iphone_sales'].min()

5.03

In [75]:
# median value of iphone sales
df['iphone_sales'].median()

17.130000000000003

In [76]:
# standard deviation of iphone sales
df['iphone_sales'].std()

7.180076841751312

In [77]:
# total non-nulll values in the column
df['iphone_sales'].count()

np.int64(1000)

## unique and frequency values

In [78]:
# list of unique values in region
df['Region'].unique()

array(['China', 'EU', 'Rest of Asia', 'North America', 'Rest of World'],
      dtype=object)

In [79]:
# nummber of unique values in region
df['Region'].nunique()

5

In [80]:
# count of each unique values in region
df['Region'].value_counts()

Region
Rest of World    221
China            219
EU               204
Rest of Asia     178
North America    178
Name: count, dtype: int64

## row-wise calculations

In [81]:
# add multiple columns across each row
df['total_units']=df[['iphone_sales','ipad_sales','mac_sales']].sum(axis=1)
df['total_units']

0      15.40
1      29.72
2      28.48
3      25.57
4      31.29
       ...
995    47.56
996    49.24
997    41.06
998    32.39
999    33.77
Name: total_units, Length: 1000, dtype: float64

In [82]:
# row wise average
df[['iphone_sales','ipad_sales','mac_sales']].mean(axis=1)

0       5.133333
1       9.906667
2       9.493333
3       8.523333
4      10.430000
         ...
995    15.853333
996    16.413333
997    13.686667
998    10.796667
999    11.256667
Length: 1000, dtype: float64

## apply math to a column

In [83]:
# multiply each iphone_sales value by 2
df['iphone_sales']*2

0      14.92
1      17.26
2      11.22
3      15.64
4      33.40
       ...
995    59.72
996    55.66
997    50.94
998    30.68
999    52.60
Name: iphone_sales, Length: 1000, dtype: float64

In [84]:
# apply custom function to each values
df['iphone_sales'].apply(lambda x:x**2)

0       55.6516
1       74.4769
2       31.4721
3       61.1524
4      278.8900
         ...
995    891.6196
996    774.5089
997    648.7209
998    235.3156
999    691.6900
Name: iphone_sales, Length: 1000, dtype: float64

## apply math to whole dataframe

In [85]:
# square root of the values in selected columns
df[['iphone_sales','ipad_sales','mac_sales']].apply(np.sqrt)

     iphone_sales  ipad_sales  mac_sales
0        2.731300    2.598076   1.090871
1        2.937686    3.749667   2.651415
2        2.368544    3.753665   2.963106
3        2.796426    2.823119   3.127299
4        4.086563    2.851315   2.541653
..            ...         ...        ...
995      5.464430    3.209361   2.720294
996      5.275415    3.538361   2.981610
997      5.046781    2.773085   2.810694
998      3.916631    2.968164   2.870540
999      5.128353    2.014944   1.846619

[1000 rows x 3 columns]

In [86]:
# log transformation for all numeric columns
df.select_dtypes(include='number').apply(np.log1p)

,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue,total_units
0,2.135349,2.047693,0.783902,1.928619,2.826129,2.797281
1,2.264883,2.712042,2.083185,2.130610,2.408745,3.424914
2,1.888584,2.714032,2.280339,2.218116,3.037354,3.383712
3,2.177022,2.193886,2.377693,1.187843,1.968510,3.279783
4,2.873565,2.211566,2.009555,1.499623,2.659560,3.474758
...,...,...,...,...,...,...
995,3.429461,2.424803,2.128232,2.360854,2.973487,3.882800
996,3.361417,2.604170,2.291524,1.697449,1.998774,3.916812
997,3.276012,2.162173,2.186051,2.066863,2.772589,3.739097
998,2.793616,2.283402,2.223542,2.280339,2.802754,3.508256
999,3.306887,1.621366,1.483875,1.900614,2.727199,3.548755

## Boolean calculations / conditons

In [87]:
# true/false for iphone_sales above 20
df['iphone_sales']>20

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998    False
999     True
Name: iphone_sales, Length: 1000, dtype: bool

In [88]:
# filter rows where condition is true
df[df['iphone_sales']>20]

,State,Region,iphone_sales,ipad_sales,mac_sales,wearables,Service_revenue,total_units
6,UK,EU,25.47,7.41,7.18,7.56,17.20,40.06
7,New York,North America,22.37,6.74,4.39,3.22,16.07,33.50
8,Mexico,Rest of World,20.80,6.79,4.99,2.68,8.69,32.58
12,Hong Kong,China,23.29,13.29,2.59,3.22,11.99,39.17
22,India,Rest of Asia,23.69,2.77,3.90,6.84,13.07,30.36
...,...,...,...,...,...,...,...,...
990,Spain,EU,22.06,10.18,5.90,5.59,12.13,38.14
995,Mexico,Rest of World,29.86,10.30,7.40,9.60,18.56,47.56
996,Texas,North America,27.83,12.52,8.89,4.46,6.38,49.24
997,Germany,EU,25.47,7.69,7.90,6.90,15.00,41.06
999,Shanghai,China,26.30,4.06,3.41,5.69,14.29,33.77

## correlation & covariance

In [89]:
# correlation matrix between numeric columns
# df.corr()

In [90]:
# covariance matrix
# df.cov()

# Apply functions and plotting

## using apply() on the column

In [91]:
# multiply every values in iphone_sales by 2
df['iphone_sales'].apply(lambda x:x * 2)

0      14.92
1      17.26
2      11.22
3      15.64
4      33.40
       ...
995    59.72
996    55.66
997    50.94
998    30.68
999    52.60
Name: iphone_sales, Length: 1000, dtype: float64

In [92]:
# round each values
df['iphone_sales'].apply(round)

0       7
1       9
2       6
3       8
4      17
       ..
995    30
996    28
997    25
998    15
999    26
Name: iphone_sales, Length: 1000, dtype: int64

In [93]:
# create new column based on condition
df['iphone_sales'].apply(lambda x:' High' if x > 20  else 'Low')

0        Low
1        Low
2        Low
3        Low
4        Low
       ...
995     High
996     High
997     High
998      Low
999     High
Name: iphone_sales, Length: 1000, dtype: object

## using apply() on rows and columns

In [94]:
# apply numpy sqrt function to each column
df[['iphone_sales','ipad_sales']].apply(np.sqrt)

     iphone_sales  ipad_sales
0        2.731300    2.598076
1        2.937686    3.749667
2        2.368544    3.753665
3        2.796426    2.823119
4        4.086563    2.851315
..            ...         ...
995      5.464430    3.209361
996      5.275415    3.538361
997      5.046781    2.773085
998      3.916631    2.968164
999      5.128353    2.014944

[1000 rows x 2 columns]

In [95]:
# apply function column-wise
df[['iphone_sales','ipad_sales']].apply(lambda x:x.max() - x.min())

iphone_sales    24.91
ipad_sales      12.97
dtype: float64

## using applymap() for element-wise on dataframe

In [96]:
# multiply every element by 10
df[['iphone_sales','ipad_sales']].apply(lambda x:x * 10)

     iphone_sales  ipad_sales
0            74.6        67.5
1            86.3       140.6
2            56.1       140.9
3            78.2        79.7
4           167.0        81.3
..            ...         ...
995         298.6       103.0
996         278.3       125.2
997         254.7        76.9
998         153.4        88.1
999         263.0        40.6

[1000 rows x 2 columns]

## using map() on a series

In [97]:
df['Region'].map({'China':1,'EU':2})

0      1.0
1      2.0
2      2.0
3      1.0
4      NaN
      ...
995    NaN
996    NaN
997    2.0
998    1.0
999    1.0
Name: Region, Length: 1000, dtype: float64